before_cache:
  - find "${HOME}"/.ivy2/cache -name "ivydata-*.properties" -print -delete
cache:
  directories:
    - ${HOME}/.ivy2/cache

env:
  - RUNNER_IMAGE="constellationapplication/netbeans-runner:12"

# Disable shallow clone for SCM SonarCloud analysis
git:
  depth: false

jobs:
  include:
  - stage: Build and Test
    dist: bionic
    language: java
    services:
      - docker
    before_install:
      - pwd
      - git clone https://github.com/constellation-app/constellation.git /home/travis/build/constellation-app/constellation
      - ls -l ../*
    script:
      - docker pull "${RUNNER_IMAGE}"
      - docker run --mount "type=bind,source=/home/travis/build/constellation-app,target=/home/travis/build/constellation-app" --mount "type=bind,source=${HOME}/.ivy2/cache,target=/root/.ivy2/cache" --workdir "/home/travis/build/constellation-app" "${RUNNER_IMAGE}" .travis/run-tests.sh
      - .travis/sonar.sh
    addons:
      sonarcloud:
        organization: "constellation-app"
        token: $SONAR_TOKEN

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/82ac70bdb3f9e144d859
    on_success: change
    on_failure: always
    on_start: never
